source 'http://rubygems.org'

gem 'rake'
gem 'sanitize'
gem "liquid-c"

group :development, :test do
  gem 'pry'
  gem 'html-proofer'
end

group :jekyll_plugins do
  gem 'jekyll', '>= 4.2.1'
  gem 'jekyll-paginate'
  gem 'support-for'
  gem 'jekyll-seo-tag', '>= 2.8.0'
  gem 'jekyll-sitemap'
  gem "jekyll-include-cache"
end
