source 'http://rubygems.org'

gem 'rake'
gem 'sanitize', '>= 6.0.1'
gem "liquid-c"

group :development, :test do
  gem 'pry'
  gem 'html-proofer'
end

group :jekyll_plugins do
  gem 'jekyll'
  gem 'jekyll-paginate'
  gem 'support-for'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem "jekyll-include-cache"
end
