source 'http://rubygems.org'

gem 'rake'
gem 'sanitize', '>= 6.0.0'
gem "liquid-c"

group :development, :test do
  gem 'pry'
  gem 'html-proofer', '>= 3.19.3'
end

group :jekyll_plugins do
  gem 'jekyll'
  gem 'jekyll-paginate'
  gem 'support-for'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem "jekyll-include-cache"
end
